fastify/workflows

- .github/workflows/plugins-ci.yml
- README.md
Created a basic reusable GitHub Action workflow that can be used across all of the plugins in the Fastify org.
Also integrates changes to coveralls actions as mentioned in https://github.com/fastify/fastify/issues/3328, and the latest fastify/github-action-merge-dependabot version.
> chore: add reusable plugin workflow

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
- README.md
Not 100% on if an empty string is acceptable as the default for `excludes` for [fastify/github-action-merge-dependabot](https://github.com/fastify/github-action-merge-dependabot), which is what [string inputs fall back to](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs).
Tackles https://github.com/fastify/workflows/pull/11#issuecomment-1046287233
> feat: add `auto-merge-exclude` workflow input

- .github/workflows/plugins-ci.yml
It’s important that we automerge major updates as they are the only ones that will be opened in most of our repos because we do not use lockfiles.
Let’s trust our tests to detect any potential breakage.
> Automerge major dependency updates to reduce traffic

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
Hello.
This PR aims to :
- drop Node.js version 10 whose support has ended since 04/30/2021
- drop Node.js version 12 whose support ends 04/30/2022
> ci: drop Node.js 10 and 12

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
Invalid syntax because `:` is a syntax. YAML cannot identify should it be a `key-value` pair inside `[ ]`
It requires a explicit `quote` in this case.
> fix: mysql and postgres workflow

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
See option description at https://github.com/actions/checkout#usage.
We don't use git in any `run` commands after checking out the repo, so best to just remove the git credentials for security sake.
> chore: remove git credentials after checkout

- .github/workflows/plugins-ci-postgres.yml
Seems it is required.
See https://github.com/fastify/fastify-postgres/blob/master/.github/workflows/ci.yml#L40
> fix(plugins-ci-postgres): allow scripts to be run on install

- package.json
Don't want any automated scripts rolling through and accidentally publishing this to NPM.
> chore(package): set `"private": true` to prevent pub to npm

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
> ci: disable license-checking for variant workflows

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
See https://github.com/fastify/session/pull/104
If the `license-checker` and `linter` jobs are not enabled via inputs then it skips the `test` job.
> fix: remove `needs`

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
See https://github.com/fastify/fastify-oauth2/pull/169#issuecomment-1202289206
Only consideration: Dont we need then to ship the code with the text of the Apache-2.0 license?
> add Apache-2.0 to allowed licenses

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
0BSD is a variation of ISC
So we are on the safe side. 
https://opensource.org/licenses/0BSD
Necessary to handle tslib 
https://github.com/fastify/releasify/pull/235#issuecomment-1202473519
> add 0BSD License as allowed license

- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci.yml
- README.md
I added a license-check-allowed-additional option. I will test it in my personal org.
> add license-check-allowed-additional

- .github/workflows/plugins-ci-postgres.yml
Without the newlines the commands were all being ran on the same line as if they were a single command, so `npm i` was also trying to install `sudo apt-get install -yqq libpq-dev postgresql-client`
> fix(plugins-ci-postgres): add newlines for folded block

- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
I don't think CI on Windows with Node.js v14 is recoverable. Let's just skip it everywhere.
> Skip Windows on Node.js v14

- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
fix:
- #80
Example of usage:
```yaml
strategy:
matrix:
os: [macos-latest, windows-latest]
version: [12, 14, 16]
environment: [staging, production]
exclude:
- os: macos-latest
version: 12
environment: production
- os: windows-latest
version: 16
runs-on: ${{ matrix.os }}
```
from [Github Actions docs - Using a matrix for your jobs - Excluding matrix configurations](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#excluding-matrix-configurations)
> fix invalid definition in `plugins-ci` and `plugins-ci-redis`

- .github/workflows/validate-workflows-files.yml
- Adds read only permissions to workflow
- Only allows job to run on changes to `.github/workflows/`
> ci(validate-workflows-files): restrict job permissions

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-benchmark.yml
- README.md
Resolves #89 
You can see an example output here: https://github.com/Uzlopak/fast-json-stringify/pull/4#issuecomment-1666122071
Can be integrated like this:
```yml
name: Benchmark PR
on:
pull_request_target:
types: 
- labeled
jobs:
benchmark:
if: ${{ github.event.label.name == 'benchmark' }}
uses: fastify/workflows/.github/workflows/plugins-benchmark-pr.yml@main
with:
npm-script: bench
remove-label:
if: "always()"
needs: 
- benchmark
runs-on: ubuntu-latest
steps:
- name: Remove benchmark label
uses: octokit/request-action@v2.x
id: remove-label
with:
route: DELETE /repos/{repo}/issues/{issue_number}/labels/{name}
repo: ${{ github.event.pull_request.head.repo.full_name }}
issue_number: ${{ github.event.pull_request.number }}
name: benchmark
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` …
> feat: add plugins-benchmark-pr.yml

- README.md
Adding the `permissions` config.
New repos (or just me??) do not allow permessive github token:
So these `permissions` are necessary to avoid the error:
```
[Invalid workflow file: .github/workflows/ci.yml#L14](https://github.com/Eomm/fastify-telegram/actions/runs/6449305117/workflow)
The workflow is not valid. .github/workflows/ci.yml (Line: 14, Col: 3): Error calling workflow 'fastify/workflows/.github/workflows/plugins-ci.yml@v3'. The nested job 'automerge' is requesting 'contents: write, pull-requests: write', but is only allowed 'contents: read, pull-requests: none'.
```
> docs: add permissions in readme

- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
Node 21 got released. We should also test against node 21 to ensure we detect breaking changes early.
> chore: add node21 to the test matrix

- .github/workflows/plugins-ci.yml
Tested with https://github.com/fastify/light-my-request/pull/269
> improve workflow with fastify-integration job

- .github/workflows/plugins-ci-redis.yml
Resolves CI errors in fastify-redis: https://github.com/fastify/fastify-redis/actions/runs/6668185090/workflow
We only test on ubuntu anyway in this workflow, so the exclusion is redundant.
> fix(plugins-ci-redis): remove exclusion of windows node 14

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
- README.md
Drop node <= 16 from workflows
Add node 21 to benchmark-pr
Add node 21 to ci-package-manager for yarn
Fixes #106, #92.
> Updates for fastify v5

- CONTRIBUTING.md
- README.md
> docs(contributing): add contributing guide

- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
> The OpenJS Board of Directors still need to vote to approve the Blue Oak license for OpenJS-hosted projects. The vote will take place this week.
https://github.com/fastify/workflows/issues/97#issuecomment-1915687184
> adds BlueOak-1.0.0

- .github/workflows/plugins-benchmark-pr.yml
- README.md
Closes fastify/workflows#93
Previously, the second benchmark run ran against the default branch of the (potentially forked) repo, which might not be in sync with the PR target repo.
> fix(plugins-benchmark-pr): run comparison benchmark against target

- .github/workflows/plugins-ci-elasticsearch.yml
> add elasticsearch ci

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-ci-kafka.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
- README.md
This will let us use the centralized workflow for most _libraries_
Examples of where it will be used if merged:
https://github.com/fastify/proxy-addr/pull/61#pullrequestreview-2003940510
https://github.com/fastify/fluent-json-schema/pull/242
https://github.com/fastify/process-warning/pull/104
and other `@fastify/libraries` repos
> Make node versions dynamic

- .github/workflows/plugins-ci-elasticsearch.yml
> add node-versions to elastic ci

- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci.yml
Related to https://github.com/fastify/.github/issues/37.
This is just a proposal, probably not comprehensive of all the places where a similar change may have to occur, simply to capture that this is possible (and I didn't know until now) to exclude combinations, as documented in https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#excluding-matrix-configurations
> chore: exclude Node 14 and 16 on macos

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-ci-elasticsearch.yml
- .github/workflows/plugins-ci-kafka.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
- README.md
https://github.com/fastify/fastify/issues/5460
> remove node 18 and add node 22

- .github/workflows/plugins-ci-elasticsearch.yml
Since the elasticsearch docker image version `8.13.2` is [not available anymore](https://hub.docker.com/_/elasticsearch/tags?name=8.13) (as discovered during https://github.com/fastify/fastify-elasticsearch/pull/118) updates the image to [`8.15.2` version](https://hub.docker.com/_/elasticsearch/tags?name=8.15.2).
> fix: update elasticsearch docker image version to `8.15.2`

- .github/workflows/plugins-ci-elasticsearch.yml
In order to avoid tagging new versions of this repository whenever a new version of elasticsearch image is released or doesn't exist anymore on Docker Hub, extracts the image version as a workflow input.
This will allow driving the version being used from https://github.com/fastify/fastify-elasticsearch/blob/master/.github/workflows/ci.yml directly.
> chore: extract elasticsearch image version

- README.md
Was introduced as part of #99 
> docs(readme): add missing `fastify-dependency-integration` input

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-ci-elasticsearch.yml
- .github/workflows/plugins-ci-kafka.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
- .github/workflows/release.yml
This PR enables the `check-latest` option for all action/setup-node steps, which ensures that the latest Node version is used that satisfies the version spec.
I.e. whenever we're using a version like `22`, `22.x` or `lts/*` it'll ensure we're using 22.12.0 (at time of writing).
This avoids an old cached version from being used in actions.
See https://github.com/actions/setup-node?tab=readme-ov-file#usage
We'll want this to get [22.13.0 when it becomes available](https://github.com/nodejs/node/pull/56329) to fix https://github.com/nodejs/node/issues/56137, which is currently plaguing our CI jobs across most repos, otherwise we may still be using a cached version of 22.12.0.
> refactor: use latest node version

- .github/workflows/plugins-ci.yml
Allows for this workflow to be used by fast-uri, which is still supporting Node 10+ due to ajv.
See https://github.com/fastify/fast-uri/pull/119
> fix(plugins-ci): exclude node 10 and 12 on macos

- .github/workflows/release.yml
- .github/workflows/validate-workflows-files.yml
This PR is created by a script. Please check the changes prior to merging.
This PR adds permissions to the workflow and job level, making the workflows read-only by default, and allowing write access only at the job level via granular permissions. This is regularly flagged by CodeQL, Step Security, [OSSF](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions), and other security tools.
This change also allows the org to go read-only everywhere, see https://github.com/fastify/avvio/pull/308#issuecomment-2765300174
> ci: set workflow permissions to read-only by default

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-ci-elasticsearch.yml
- .github/workflows/plugins-ci-kafka.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
- .github/workflows/release.yml
- .github/workflows/validate-workflows-files.yml
After what has been happening with [tj-actions/changed-files](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised) over the past week this is probably a sensible idea.
@rafaelgss [even wrote about it a while back](https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash)!
> build(.github): pin actions to commit-hash

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-ci-elasticsearch.yml
- .github/workflows/plugins-ci-kafka.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-package-manager.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
- .github/workflows/release.yml
- .github/workflows/validate-workflows-files.yml
Most first party actions now use https://github.com/actions/publish-immutable-action, which negates the need for commit hashes
> ci: use tags for immutable github actions

- .github/workflows/plugins-benchmark-pr.yml
- .github/workflows/plugins-ci-elasticsearch.yml
- .github/workflows/plugins-ci-kafka.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
This was covered in the GitHub Secure Open Source Fund program that [Fastify participated in](https://github.blog/open-source/maintainers/securing-the-supply-chain-at-scale-starting-with-71-important-open-source-projects/#web-servers-networking-and-gateways-%f0%9f%96%a5%ef%b8%8f).
See https://securitylab.github.com/resources/github-actions-untrusted-input/ for supporting documentation.
> fix: avoid potential code injection

- .github/workflows/plugins-ci-elasticsearch.yml
- .github/workflows/plugins-ci-kafka.yml
- .github/workflows/plugins-ci-mongo.yml
- .github/workflows/plugins-ci-mysql.yml
- .github/workflows/plugins-ci-postgres.yml
- .github/workflows/plugins-ci-quality.yml
- .github/workflows/plugins-ci-redis.yml
- .github/workflows/plugins-ci.yml
Closes #70.
Cuts down on duplicate steps across workflows. Now if we need to amend linting and quality check steps we can just update one workflow instead of multiple.
> refactor: move linting, dep checks, and license checks to own workflow
