.github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, README.md
=> feat: add service variants

.github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci.yml, README.md
closes #6, will require major bump as removing feature
=> chore!: remove coveralls jobs from workflows

.github/dependabot.yml, .github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci.yml
=> build: add dependabot config

.github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci.yml
This is the pendant to https://github.com/fastify/fastify/pull/3885
=> run automerge only in pull-requests by dependabot

.github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci.yml
See https://github.com/fastify/fastify/issues/3883
=> ci: add dependency-review job

.github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci.yml
- Added missing `linter` job to workflow variants
- Removed `macos-latest` and `windows-latest` from DB workflow variants as they use service containers to stand up database instances, [which can only be used with Linux containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers#about-service-containers)
- Added names, whitespace, and reorder values, to improve readability
=> fix: add missing `linter` job to workflow variants

.github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci.yml
Adds a job to check licenses like it is done in fastify core project
=> add license-check

.github/workflows/plugins-ci.yml
Ref: https://github.com/fastify/fastify-passport/pull/597
Ref: https://github.com/fastify/fastify-passport/pull/607
=> Drop dependency review as it's imprecise

.github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci.yml, .github/workflows/release.yml, README.md
=> chore: tidy workflows; add `license-check` documentation

.github/workflows/plugins-ci-redis.yml
=> add redis workflow

.github/workflows/plugins-ci-mongo.yml
=> add mongo workflow

.github/workflows/plugins-ci-mongo.yml, .github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci-redis.yml, .github/workflows/plugins-ci.yml
=> ci: reduce license checking verbosity

.github/workflows/plugins-ci-mongo.yml, .github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci-redis.yml, .github/workflows/plugins-ci.yml
Should be merged when we / @simoneb release/s a new version of github-action-merge-dependabot
=> recommend semicolon instead of comma

.github/workflows/plugins-ci-postgres.yml
=> fix(plugins-ci-postgres): remove `--ignore-scripts` arg

README.md
[Yeovil District Hospital NHS Foundation Trust is due to ~merge with~ be taken over by Somerset NHS Foundation Trust](https://yeovilhospital.co.uk/better-care-for-local-people-the-merger-of-yeovil-hospital-nhs-foundation-trust-with-somerset-nhs-foundation-trust/) in April 2023, and will cease to exist.
=> docs(readme): update acknowledgements section

.github/workflows/plugins-ci-mongo.yml, .github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci-redis.yml, .github/workflows/plugins-ci.yml
=> ci: add node 20 to test matrix

.github/workflows/plugins-ci-package-manager.yml
=> ci: add reusable package manager CI workflow

.github/workflows/validate-workflows-files.yml
@bcomnes, v0.5.3 may resolve the issue with #87.
=> ci(validate-workflow-files): bump action-validator

.github/workflows/plugins-ci-mongo.yml, .github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci-redis.yml, .github/workflows/plugins-ci.yml
=> feat(backport): add blue-oak v1.0.0 (#116) 

.github/workflows/plugins-ci-kafka.yml
=> add kafka workflow

.github/workflows/plugins-ci-kafka.yml
fixes binding errors https://github.com/gurgunday/fastify-kafka/actions/runs/9812226247/job/27095873773
=> fix: kafka binding erros

README.md
=> docs(readme): update example workflow versions

.github/workflows/plugins-benchmark-pr.yml
=> ci(plugins-benchmark-pr): drop old node versions

.github/workflows/plugins-benchmark-pr.yml, README.md
=> style: remove trailing whitespace

package.json
=> chore(package): add contribs and funding

README.md
=> docs(readme): update example permissions

README.md
=> ci: restore job level permissions

.github/workflows/plugins-benchmark-pr.yml
Missed this in https://github.com/fastify/workflows/pull/164
=> fix(plugins-benchmark-pr): replace node 23 with 24

.github/workflows/plugins-benchmark-pr.yml
Got the wrong one initially, should have been https://github.com/thollander/actions-comment-pull-request/commit/24bffb9b452ba05a4f3f77933840a6a841d1b32b
=> ci: fix thollander/actions-comment-pull-request commit-hash

.github/workflows/plugins-ci-elasticsearch.yml, .github/workflows/plugins-ci-kafka.yml, .github/workflows/plugins-ci-mongo.yml, .github/workflows/plugins-ci-mysql.yml, .github/workflows/plugins-ci-postgres.yml, .github/workflows/plugins-ci-redis.yml, .github/workflows/plugins-ci.yml
See https://github.com/fastify/fastify/pull/6330. This is a batch PR created by a script. Please review prior to merging.
=> ci: check dependabot prs originate from repo
